// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace BDDTest.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class BloodPressureCategoryCalculationFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Blood Pressure Category Calculation", "  In order to classify blood pressure readings correctly\r\n  As a health system\r\n " +
                " I want to determine the BP category based on systolic and diastolic values", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "Calculator.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute(Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupBehavior.EndOfClass)]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Calculator.feature.ndjson", 18);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("High Blood Pressure")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("High Blood Pressure")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Blood Pressure Category Calculation")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("HighBP")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("140", "70", "0", null, DisplayName="High Blood Pressure(140,70,0)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("120", "90", "1", null, DisplayName="High Blood Pressure(120,90,1)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("160", "95", "2", null, DisplayName="High Blood Pressure(160,95,2)")]
        public async global::System.Threading.Tasks.Task HighBloodPressure(string systolic, string diastolic, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "HighBP"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Systolic", systolic);
            argumentsOfScenario.Add("Diastolic", diastolic);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("High Blood Pressure", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 7
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
    await testRunner.GivenAsync(string.Format("a systolic value of {0}", systolic), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 9
    await testRunner.AndAsync(string.Format("a diastolic value of {0}", diastolic), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 10
    await testRunner.WhenAsync("the blood pressure category is calculated", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 11
    await testRunner.ThenAsync("the result should be \"High\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Pre-High Blood Pressure")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Pre-High Blood Pressure")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Blood Pressure Category Calculation")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("PreHighBP")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("130", "70", "3", null, DisplayName="Pre-High Blood Pressure(130,70,3)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("125", "85", "4", null, DisplayName="Pre-High Blood Pressure(125,85,4)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("119", "82", "5", null, DisplayName="Pre-High Blood Pressure(119,82,5)")]
        public async global::System.Threading.Tasks.Task Pre_HighBloodPressure(string systolic, string diastolic, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "PreHighBP"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Systolic", systolic);
            argumentsOfScenario.Add("Diastolic", diastolic);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Pre-High Blood Pressure", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 20
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 21
    await testRunner.GivenAsync(string.Format("a systolic value of {0}", systolic), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 22
    await testRunner.AndAsync(string.Format("a diastolic value of {0}", diastolic), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 23
    await testRunner.WhenAsync("the blood pressure category is calculated", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 24
    await testRunner.ThenAsync("the result should be \"PreHigh\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Ideal Blood Pressure")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Ideal Blood Pressure")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Blood Pressure Category Calculation")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("IdealBP")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("100", "70", "6", null, DisplayName="Ideal Blood Pressure(100,70,6)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("118", "65", "7", null, DisplayName="Ideal Blood Pressure(118,65,7)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("90", "60", "8", null, DisplayName="Ideal Blood Pressure(90,60,8)")]
        public async global::System.Threading.Tasks.Task IdealBloodPressure(string systolic, string diastolic, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "IdealBP"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Systolic", systolic);
            argumentsOfScenario.Add("Diastolic", diastolic);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Ideal Blood Pressure", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 33
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 34
    await testRunner.GivenAsync(string.Format("a systolic value of {0}", systolic), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 35
    await testRunner.AndAsync(string.Format("a diastolic value of {0}", diastolic), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 36
    await testRunner.WhenAsync("the blood pressure category is calculated", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 37
    await testRunner.ThenAsync("the result should be \"Ideal\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Low Blood Pressure")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Low Blood Pressure")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Blood Pressure Category Calculation")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("LowBP")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("85", "55", "9", null, DisplayName="Low Blood Pressure(85,55,9)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("75", "45", "10", null, DisplayName="Low Blood Pressure(75,45,10)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("89", "59", "11", null, DisplayName="Low Blood Pressure(89,59,11)")]
        public async global::System.Threading.Tasks.Task LowBloodPressure(string systolic, string diastolic, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "LowBP"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Systolic", systolic);
            argumentsOfScenario.Add("Diastolic", diastolic);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Low Blood Pressure", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 46
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 47
    await testRunner.GivenAsync(string.Format("a systolic value of {0}", systolic), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 48
    await testRunner.AndAsync(string.Format("a diastolic value of {0}", diastolic), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 49
    await testRunner.WhenAsync("the blood pressure category is calculated", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 50
    await testRunner.ThenAsync("the result should be \"Low\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Out-of-range Values")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Out-of-range Values")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Blood Pressure Category Calculation")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("OutOfRange")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("60", "50", "12", null, DisplayName="Out-of-range Values(60,50,12)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("200", "80", "13", null, DisplayName="Out-of-range Values(200,80,13)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("120", "30", "14", null, DisplayName="Out-of-range Values(120,30,14)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("120", "150", "15", null, DisplayName="Out-of-range Values(120,150,15)")]
        public async global::System.Threading.Tasks.Task Out_Of_RangeValues(string systolic, string diastolic, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "OutOfRange"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Systolic", systolic);
            argumentsOfScenario.Add("Diastolic", diastolic);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Out-of-range Values", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 59
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 60
    await testRunner.GivenAsync(string.Format("a systolic value of {0}", systolic), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 61
    await testRunner.AndAsync(string.Format("a diastolic value of {0}", diastolic), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 62
    await testRunner.WhenAsync("the blood pressure category is retrieved", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 63
    await testRunner.ThenAsync("an out of range exception should be thrown", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
